.SUFFIXES: .c .o

OBJDIR= /usr/obj/

KMOD= hfs 
SRCS= hfsplus/hfs_vfsops.c \
	hfsplus/hfs_vnops.c \
	hfsplus/hfs_cnode.c \
	hfsplus/hfs_chash.c \
	hfsplus/hfs_catalog.c \
	hfsplus/hfs_encodings.c \
	hfsplus/hfs_vfsutils.c \
	hfsplus/hfs_endian.c \
	hfsplus/hfs_encodinghint.c \
	hfsplus/hfs_quota.c \
	hfsplus/rangelist.c \
	hfsplus/hfscommon/Misc/FileExtentMapping.c \
	hfsplus/hfscommon/Misc/VolumeAllocation.c \
	hfsplus/hfscommon/Misc/BTreeWrapper.c \
	hfsplus/hfscommon/Catalog/CatalogUtilities.c \
	hfsplus/hfs_btreeio.c \
	hfsplus/hfscommon/Catalog/Catalog.c \
	hfsplus/hfscommon/Catalog/CatalogIterators.c \
	hfsplus/hfs_readwrite.c \
	hfsplus/hfs_macos_stubs.c \
	vfs/vfs_utfconv.c \
	hfsplus/hfscommon/BTree/BTree.c \
	hfsplus/hfscommon/BTree/BTreeTreeOps.c \
	hfsplus/hfscommon/BTree/BTreeMiscOps.c \
	hfsplus/hfscommon/BTree/BTreeNodeOps.c \
	hfsplus/hfscommon/BTree/BTreeAllocate.c \
	hfsplus/hfscommon/Unicode/UnicodeWrappers.c \
	hfsplus/hfs_attrlist.c \

SRCS+= vnode_if.h

SYSDIR?= /usr/src

CFLAGS+= -I${.CURDIR} -DKERNEL -g

.include <bsd.kmod.mk>
