.SUFFIXES: .c .o

OBJDIR= /usr/obj/

KMOD= hfs 
SRCS= hfsplus/hfs_vfsops.c \
	hfsplus/hfs_vnops.c \
	hfsplus/hfs_cnode.c \
	hfsplus/hfs_chash.c \
	hfsplus/hfs_encodings.c \
	hfsplus/hfs_vfsutils.c \
	hfsplus/hfscommon/Misc/FileExtentMapping.c \
	hfsplus/hfs_btreeio.c \

SRCS+= vnode_if.h

SYSDIR?= /usr/src

CFLAGS+= -I${.CURDIR} -DKERNEL

.include <bsd.kmod.mk>
