#!/bin/sh

init() {
    mdconfig -a -t vnode -f /plus_hfs.dmg -u 10 
    mdconfig -a -t vnode -f /plain_hfs.dmg -u 11 
}

build() {
    make clean && make obj && make
}

load() {
    kldload /usr/obj/sharedcode/hfs.ko
}

test_mount() {
    mount -t hfs -o hfs_uid=1000,hfs_gid=1000 /dev/md12 /hello
}

default() {
    echo "<---Building--->"
    build 
    echo "<---Loading kmod--->"
    load 
    echo "<---Testing mount--->"
    test_mount 
}

if [ $# -eq 0 ]; then
    default
else
    "$@"
fi
